# GrExercise 1 - Flying Around

## Hua Wang
## 2016SU_PREDICT_420-DL_SEC55

In [2]:
#create lables for airports
airports_labels = open("airports_label.txt", "r")
airports_label = airports_labels.readline() 
apLabels = airports_label.replace(" ", "").split(',')
print apLabels

['airportID', 'name', 'city', 'country', 'iataFaa', 'icao', 'latitude', 'longitude', 'Altitude', 'timezone', 'dst', 'tz']

In [3]:
#create label for routes
routes_labels = open("routes_label.txt", "r")
routes_label = routes_labels.readline() 
rtLabels = routes_label.replace(" ", "").split(',')
print rtLabels

['airline', 'airlineID', 'sourceAp', 'sourceApID', 'destinationAirport', 'destinationApID', 'codeshare', 'stops', 'equipment']

In [4]:
#creare label for airlines
airlines_labels = open("airlines_label.txt", "r")
airlines_label = airlines_labels.readline() 
alLables = airlines_label.replace(" ", "").split(',')
print alLables

['airlineID', 'name', 'alias', 'iata', 'icao', 'callsign', 'country', 'active']

In [5]:
#read files into pandas as dataframe
import pandas as pd

airports = pd.read_csv('airports.dat', encoding='latin-1',sep=',', header=None)
routes = pd.read_csv('routes.dat',encoding='latin-1',sep=',',header=None)
airlines = pd.read_csv('airlines.dat',encoding='latin-1',sep=',',header=None)

In [6]:
#assign labels to dataframes
airports.columns = apLabels
routes.columns = rtLabels
airlines.columns = alLables

In [7]:
#check duplcate records in airports dataframe
airportsCount = airports.groupby(['name', 'iataFaa', 'timezone']).size().reset_index().rename(columns={0:'count'})
airportsCount.loc[airportsCount['count'] != 1]

                   name iataFaa  timezone  count
198  Amsterdam Centraal     ZYA       1.0      2

In [8]:
#check duplcate records in routes dataframe
routesCount = routes.groupby(['airlineID','sourceAp','sourceApID', 'destinationAirport','destinationApID']).size().reset_index().rename(columns={0:'count'})
routesCount.loc[routesCount['count'] != 1]

      airlineID sourceAp sourceApID destinationAirport destinationApID  count
67034        \N      BZE       1957                FRS            4024      2
67108        \N      FLL       3533                MHH            1930      2
67113        \N      FRS       4024                BZE            1957      2
67211        \N      MHH       1930                FLL            3533      2
67435        \N      YKL         80                YWK             161      2
67494        \N      YQB        111                YUL             146      2
67498        \N      YQB        111                YZV             202      2
67532        \N      YUL        146                YQB             111      2
67568        \N      YWK        161                YKL              80      2
67572        \N      YWK        161                YZV             202      3
67631        \N      YZV        202                YQB             111      2
67633        \N      YZV        202                YWK             161      3

In [9]:
#check duplcate records in airlines dataframe
airlinesCount = airlines.groupby(['name','iata','icao', 'callsign','country','active']).size().reset_index().rename(columns={0:'count'})
airlinesCount.loc[airlinesCount['count'] != 1]

Empty DataFrame
Columns: [name, iata, icao, callsign, country, active, count]
Index: []

In [10]:
airports.dtypes

airportID      int64
name          object
city          object
country       object
iataFaa       object
icao          object
latitude     float64
longitude    float64
Altitude       int64
timezone     float64
dst           object
tz            object
dtype: object

In [11]:
routes.dtypes

airline               object
airlineID             object
sourceAp              object
sourceApID            object
destinationAirport    object
destinationApID       object
codeshare             object
stops                  int64
equipment             object
dtype: object

In [12]:
airlines.dtypes

airlineID     int64
name         object
alias        object
iata         object
icao         object
callsign     object
country      object
active       object
dtype: object

In [13]:
airlines[airlines['active']=='N'].count()

#4886 rows are defunc

airlineID    4886
name         4886
alias        4789
iata          503
icao         4828
callsign     4413
country      4873
active       4886
dtype: int64

In [14]:
#cast sourceApID to int
routes['sourceApID'] = routes['sourceApID'].astype(str)
airports['airportID'] = airports['airportID'].astype(str)

merged_left = pd.merge(left=routes,right=airports, how='left', left_on='sourceApID', right_on='airportID')
nowhereFlights = merged_left[merged_left['airportID'].isnull()]
nowhereFlights

,airline,airlineID,sourceAp,sourceApID,destinationAirport,destinationApID,codeshare,stops,equipment,airportID,...,city,country,iataFaa,icao,latitude,longitude,Altitude,timezone,dst,tz
38,2B,410,TGK,\N,DME,4029,NaN,0,CR2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,2G,1654,KCK,\N,IKT,2937,NaN,0,AN4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1163,4O,17885,PQM,\N,MEX,1824,NaN,0,SU9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1714,4W,\N,SVS,\N,FAI,3832,NaN,0,PA2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1715,4W,\N,SVS,\N,WBQ,7115,NaN,0,PA2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1736,4Y,1173,KKI,\N,AKI,7217,NaN,0,CNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1747,4Y,1173,PKA,\N,BET,3599,NaN,0,CNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,4Y,1173,WNA,\N,PKA,\N,NaN,0,CNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1877,5J,1683,IAO,\N,CEB,4206,NaN,0,ATR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2113,5Z,18946,PBZ,\N,CPT,797,NaN,0,BEH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2114,5Z,18946,PBZ,\N,JNB,813,NaN,0,BEH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2650,7H,16726,KKI,\N,AKI,7217,Y,0,CNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2651,7H,16726,KKI,\N,KWT,7095,Y,0,CNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2867,7P,1500,OGM,\N,MPP,8207,NaN,0,DHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3213,8P,3856,YKT,\N,ZEL,7275,NaN,0,DHP,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3310,8T,68,YFJ,\N,YZF,196,NaN,0,DHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3394,8V,55,LMA,\N,FAI,3832,NaN,0,PAG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3556,9C,15999,ZYI,\N,KMG,3382,NaN,0,320,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3557,9C,15999,ZYI,\N,SHA,3391,NaN,0,320,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3777,9N,\N,SQS,\N,BCV,8227,NaN,0,CNC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3778,9N,\N,SQS,\N,BZE,1957,NaN,0,CNC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3779,9N,\N,SQS,\N,SPR,4279,NaN,0,CNC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3780,9N,\N,SQS,\N,TZA,6463,NaN,0,CNC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4468,A4,4550,ORU,\N,CBB,2759,NaN,0,SWM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4469,A4,4550,ORU,\N,SRZ,4247,NaN,0,SWM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4635,A8,1392,KSE,\N,EBB,1187,NaN,0,CNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8741,AD,13983,PHB,\N,FOR,2559,NaN,0,AT7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8742,AD,13983,PHB,\N,THE,2623,NaN,0,AT7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10139,AH,794,CFK,\N,MRS,1353,NaN,0,736,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10158,AH,794,EBH,\N,ALG,210,NaN,0,ATR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60722,V0,1886,CBS,\N,CCS,2851,NaN,0,ATR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60949,V9,10800,VLY,\N,CWL,488,NaN,0,J31,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61052,VA,5360,DCN,\N,PER,3351,NaN,0,320 100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61869,VT,692,KHZ,\N,KXU,\N,NaN,0,ATR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61871,VT,692,KXU,\N,PPT,4075,NaN,0,ATR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61918,VT,692,RKA,\N,KHZ,\N,NaN,0,ATR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62497,W3,407,ABB,\N,ABV,260,NaN,0,73G,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62498,W3,407,ABB,\N,LOS,273,NaN,0,73G,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62534,W3,407,GMO,\N,ABV,260,NaN,0,CR9 DH4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62569,W3,407,QUO,\N,LOS,273,NaN,0,CR9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62578,W4,16660,JAU,\N,LIM,2789,NaN,0,DH8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62586,W4,16660,TGI,\N,LIM,2789,NaN,0,DH8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63026,W6,5461,TZL,\N,GSE,691,NaN,0,320,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63027,W6,5461,TZL,\N,MLH,1423,NaN,0,320,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63028,W6,5461,TZL,\N,MMX,708,NaN,0,320,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63371,WJ,5399,YNP,\N,YDP,5488,NaN,0,DHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63372,WJ,5399,YNP,\N,YHO,5502,NaN,0,DHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63381,WJ,5399,ZGS,\N,YHR,5503,NaN,0,DHT BE1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63382,WJ,5399,ZGS,\N,YNA,94,NaN,0,DHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63383,WJ,5399,ZGS,\N,YZV,202,NaN,0,BE1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63384,WJ,5399,ZGS,\N,ZKG,8217,NaN,0,DHT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65963,Y7,13088,TGP,\N,KJA,4374,NaN,0,AT5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65964,Y7,13088,THX,\N,KJA,4374,NaN,0,AT5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66082,YC,9828,TQL,\N,SLY,6137,NaN,0,L4T,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66249,YT,16133,JKR,\N,KTM,3125,NaN,0,J41,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66304,Z3,1266,KWF,\N,KTN,3808,NaN,0,DHP,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66352,Z8,603,ORU,\N,CBB,2759,NaN,0,SWM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66353,Z8,603,ORU,\N,SRZ,4247,NaN,0,SWM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66822,ZH,4611,DQA,\N,PEK,3364,Y,0,737,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67437,ZH,4611,ZYI,\N,PEK,3364,Y,0,737,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
print 'Total of %d flights from nowhere observed' % len(nowhereFlights)

Total of 239 flights from nowhere observed

In [16]:

print 'The code for flight from no where as below:'
for code in nowhereFlights.sourceAp.unique():
    print code

The code for flight from no where as below:
TGK
KCK
PQM
SVS
KKI
PKA
WNA
IAO
PBZ
OGM
YKT
YFJ
LMA
ZYI
SQS
ORU
KSE
PHB
CFK
EBH
MZW
GLN
BNB
BNC
KOO
DQA
AOG
AVA
JUH
LDS
LLB
NLT
SZI
KQT
ACZ
DEF
GCH
KHY
LFM
ETR
TNW
SZE
OGD
AOQ
IKE
IOQ
IOT
IUI
JUK
JUU
KGQ
KHQ
KUZ
NIQ
NSQ
QFG
QFN
QJH
QOQ
QUV
QUW
SAE
SGG
SRK
SVR
TQA
TQI
UPK
XEQ
BPL
ERL
JIC
KCG
UGB
EKS
JJA
DOB
OKL
SXK
YIE
BUW
KAZ
MNA
EDA
NKI
OUZ
MHC
OLL
DHB
MEU
ULZ
ZQZ
INB
ORZ
SVK
IWK
DCN
KAA
MNS
YNP
MQJ
NER
SUK
RCY
TBI
MBI
BUL
DRV
FVM
CKX
TKJ
ZGS
SXI
ZBL
HOE
NGK
OSM
TCR
WAE
KCO
NOP
BTC
UTS
CBS
VLY
KHZ
KXU
RKA
ABB
GMO
QUO
JAU
TGI
TZL
TGP
THX
TQL
JKR
KWF

In [17]:
#use pickle to save dataframes
airports.to_pickle('airports.pkl') 
routes.to_pickle('routes.pkl')
airlines.to_pickle('airlines.pkl')

In [20]:
#use haversine formula to calculate distance
from math import radians, cos, sin, asin, sqrt
def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    km = 6367 * c
    return km

In [25]:
#
homeLat = 37.643490
homeLon = -122.111704

#by using the haversine distance, the airport closes to home is OAK
airports[airports['iataFaa'] == 'OAK']

,airportID,name,city,country,iataFaa,icao,latitude,longitude,Altitude,timezone,dst,tz
3354,3453,Metropolitan Oakland Intl,Oakland,United States,OAK,KOAK,37.721278,-122.220722,9,-8.0,A,America/Los_Angeles

In [30]:
depRoutes = len(routes[routes['sourceAp']=='OAK'])
print 'There are %d departing routes from this airport' %depRoutes

There are 54 departing routes from this airport

In [32]:
desRoutes = len(routes[routes['destinationAirport']=='EGO'])
print 'There are %d routes coming into the airport with the three letter code "EGO"' %desRoutes

There are 11 routes coming into the airport with the three letter code "EGO"